// Regenerates .raw_app/pages.generated.ts from the real HTML source files in /site.
//
// Why: the Windmill Raw App frontend (.raw_app/App.tsx) needs the site's HTML as
// in-memory strings so it can render them inside an <iframe srcDoc=...>. Keeping
// /site/*.html as the single source of truth (instead of hand-editing the
// generated file) means the pixel-exact design never has to be rewritten as React.
//
// Run manually with `node scripts/build-app.mjs`, or automatically in CI before
// `wmill sync push` (see .github/workflows/deploy.yml).

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');

const pages = [
  { file: 'site/index.html', export: 'HOME_HTML' },
  { file: 'site/gallery.html', export: 'GALLERY_HTML' },
];

function toTemplateLiteral(html) {
  // Escape backticks, backslashes, and ${ sequences so the HTML can be embedded
  // safely inside a JS template literal.
  return html
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

let out = `// AUTO-GENERATED by scripts/build-app.mjs — do not edit by hand.
// Source of truth: /site/index.html and /site/gallery.html
// Regenerate with: node scripts/build-app.mjs

`;

for (const { file, export: exportName } of pages) {
  const html = readFileSync(join(repoRoot, file), 'utf-8');
  out += `export const ${exportName} = \`${toTemplateLiteral(html)}\`;\n\n`;
}

const outDir = join(repoRoot, 'u/brianne/ugc_portfolio.raw_app');
mkdirSync(outDir, { recursive: true });
const outFile = join(outDir, 'pages.generated.ts');
writeFileSync(outFile, out, 'utf-8');

console.log(`Wrote ${outFile} (${(out.length / 1024).toFixed(1)} KB) from ${pages.length} source file(s).`);
